# Chistes
print('¿Qué sale de la cruza de un mono y un pato?')
input()
print('Un monopatin')
print('¿por qué vuelan los patos al sur?')
input()
print('porque caminando tardarian mucho')
print()
print('En que se parecen una familia, un bombero y un barco?')
input()
print('No sé en que se parecen')
input()
print('En que el bombero y el barco tienen casco')
input()
print('Y la familia?' , end='')
print('Bien gracias')